AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Hatfield Storage Solutions (HSS) Demo Infrastructure
  - EC2 instance for custom web UI/API workload
  - RDS MySQL database
  - S3 bucket for inventory assets
  - IAM role for EC2 to access S3

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

  DBUsername:
    Description: The database admin username
    Type: String
    Default: admin

  DBPassword:
    Description: The database admin password
    Type: String
    NoEcho: true

  LatestAmazonLinux2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  HSSInventoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub hss-inventory-${AWS::AccountId}-${AWS::Region}
      AccessControl: Private

  EC2S3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2S3Role
      Path: /

  HSSWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP, HTTPS, SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  HSSWebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: !Ref LatestAmazonLinux2AMI
      SecurityGroupIds:
        - !Ref HSSWebSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: HSS-CustomAppServer

  HSSDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: hssdb
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt HSSWebSecurityGroup.GroupId

Outputs:
  EC2PublicIP:
    Description: Public IP of custom app EC2 host
    Value: !GetAtt HSSWebServer.PublicIp

  S3BucketName:
    Description: S3 bucket for inventory
    Value: !Ref HSSInventoryBucket

  RDSEndpoint:
    Description: Endpoint of RDS MySQL
    Value: !GetAtt HSSDatabase.Endpoint.Address
